name: FPSLocker补丁自动更新

on:
  schedule:
    - cron: '0 * * * *'
  # 手动触发
  workflow_dispatch:
  # 推送到main分支时触发
  push:
    branches: [ main ]

jobs:
  download-and-process:
    runs-on: ubuntu-latest
    steps:
      # 检出代码库
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # 安装依赖项
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 运行Python脚本
      - name: Run FPSLocker_SaltySD downloader
        run: python FPSLocker_SaltySD_download.py
        
      - name: 检查并提交更改
        run: |
          # 配置Git用户信息
          git config --local user.name "Sean"
          git config --local user.email "sean19821016@gmail.com"

          # 添加文件并检查更改
          git add SaltySD.zip
          if ! git diff --cached --quiet; then
              git commit -m "FPSLocker补丁自动更新"
              git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
              echo "文件已更新并提交"
          else
              echo "没有文件更改，未提交"
          fi
