name: 定时下载文件

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 下载文件
        run: |
          curl -L -o versions.txt https://raw.githubusercontent.com/blawar/titledb/master/versions.txt
          curl -L -o fpslocker.zip https://codeload.github.com/masagrator/FPSLocker-Warehouse/zip/refs/heads/v4
        
      - name: 检查并提交更改
        run: |
          # 配置Github用户信息
          git config --local user.name "Sean"
          git config --local user.email "sean19821016@gmail.com"

          # 添加文件并检查更改
          git add versions.txt fpslocker.zip
          if ! git diff --cached --quiet; then
              git commit -m "自动更新"
              git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
              echo "文件已更新并提交"
          else
              echo "没有文件更改，未提交"
          fi
