name: 定时下载dbi_versions文件

on:  
  schedule:  
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:  
  download:  
    runs-on: ubuntu-latest  
    
    steps:  
      - name: 检出代码  
        uses: actions/checkout@v2  
    
      - name: 下载文件  
        run: |  
          curl -o versions.txt https://raw.githubusercontent.com/blawar/titledb/master/versions.txt
      - name: 推送到代码仓库
        run: |
          git config --local user.name "Sean"
          git config --local user.email "sean19821016@gmail.com"
          git add versions.txt
          git commit -m "自动更新 versions.txt"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
